import numpy as np 
import matplotlib.pyplot as plt
x=np.arange(10)
y=np.sin(x)
z=np.cos(x)
w=np.tan(x)
plt.plot(x,y,marker="*",linewidth=3,linestyle="--",color="red")
plt.plot(x,z)
plt.plot(x,w)
plt.title("matplotlib")
plt.xlabel("x")
plt.ylabel("y")
plt.legend(["Y","Z","W"],loc="upper right")
plt.grid(True)
plt.show()